spring:
  redis:
    #Redis\u670D\u52A1\u5668\u5730\u5740
    host: 127.0.0.1
    #Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
    port: 6379
    #Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
    database: 1
    #Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
    password:
    #\u94FE\u63A5\u8D85\u65F6\u65F6\u95F4
    timeout: 10000ms
    #\u8FDE\u63A5\u6C60\u914D\u7F6E(\u53EF\u4F7F\u7528Jedispool,\u8FD9\u91CC\u4F7F\u7528lettuce\u8FDE\u63A5\u6C60)
    lettuce:
      pool:
        #\u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        max-idle: 8
        #\u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 0
        #\u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236,\u9ED8\u8BA4-1\uFF09
        max-wait: -1ms
        #\u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-active: 8

