my:
  name: thinkingcao
  age: 24
  number:  ${random.int}
  uuid : ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm  ${my.name}

spring:
  profiles:
    active: dev