#Redis\u914D\u7F6E
spring:
  redis:
    #Redis\u670D\u52A1\u5668\u5730\u5740
    host: 127.0.0.1
    #Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
    port: 6379
    #Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
    password:
    #Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
    database: 0
    lettuce:
      pool:
        #\u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-active: 32
        #\u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-wait: 300ms
        #\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        max-idle: 16
        # \u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 8
        # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
        timeout: 1000


  ## \u914D\u7F6E\u6570\u636E\u5E93\u8FDE\u63A5
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/springboot-token
    username: root
    password: 123456
    ## \u4F7F\u7528druid\u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#Mybatis\u914D\u7F6E
mybatis:
  config-location: classpath:config/mybatis-config.xml  #mybatis\u914D\u7F6E\u6587\u4EF6\u4F4D\u7F6E
  mapper-locations: classpath:mapper/*.xml       #mapper.xml \u6587\u4EF6\u5730\u5740
  type-aliases-package: com.thinkingcao.springboot.entity #\u5B9E\u4F53\u7C7B\u522B\u540D


##\u6253\u5370sql
logging:
  level:
    com.thinkingcao.springboot.token.mapper: debug